### ISSUE TITLE
sofascore API

### ISSUE THREAD

**Issue by 89500007979** [shimst3r/sofascore#3]
is it possible to use this library to collect and process statistics on past football games? I am also running an analysis project and it became very interesting to me

**Comment by shimst3r** [comment]
Hi @89500007979, I didn't know a Sofa Score also existed in the context of football matches. :smile: This library is only concerned with the [sequential organ failure assessment score](https://en.wikipedia.org/wiki/SOFA_score) as used in the medical and healthcare domain.

I'll add a disclaimer to the project's README file, thank you. :+1:
